# This file was generated by GoReleaser. DO NOT EDIT.
cask "iugu" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/iugu"], must_succeed: false
    end
  end

  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "cfe5448f5ee660a641755f20306730800f8b3c69801f48b6b78e89cfdc554189"
      url "https://github.com/iugu/cli/releases/download/v#{version}/iugu_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e9a546e87d2f704d076a6a446445981aa2eaa1798f8d78e5e2a1abd2c030646c"
      url "https://github.com/iugu/cli/releases/download/v#{version}/iugu_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f121a60dc7606a6d0f7f2a527a4f85b563ee8fc195f95662cb3ac688475ac721"
      url "https://github.com/iugu/cli/releases/download/v#{version}/iugu_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c578843c8aa4fd153396488b91a97d493abbc553f56130601edf55bdb7fb8b68"
      url "https://github.com/iugu/cli/releases/download/v#{version}/iugu_#{version}_linux_amd64.tar.gz"
    end
  end

  name "iugu"
  desc "Platform 2 Console CLI for developers and their AI agents"
  homepage "https://github.com/iugu/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iugu"
  bash_completion "completions/iugu.bash"
  fish_completion "completions/iugu.fish"
  zsh_completion "completions/_iugu"

  # No zap stanza required
end
