# This file was generated by GoReleaser. DO NOT EDIT.
cask "iugu" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "a1c27849ba31fcbec0fba6b68584338f3afb0332af270e851eb6bd13dc589dde"
      url "https://github.com/iugu/cli/releases/download/v#{version}/iugu_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a9159fc069352ad1890bf601596d0b8d980db4e4bf72cc844bf8f3b0b9b9ed36"
      url "https://github.com/iugu/cli/releases/download/v#{version}/iugu_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3329aba0a85bc3147550bb7ba33448473225077721927c69e10449adef634f4b"
      url "https://github.com/iugu/cli/releases/download/v#{version}/iugu_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2139779c3ac1b53b9ff554b8be40a5becffd796a35762d798d202389bcfcabbc"
      url "https://github.com/iugu/cli/releases/download/v#{version}/iugu_#{version}_linux_amd64.tar.gz"
    end
  end

  name "iugu"
  desc "Platform 2 Console CLI for developers and their AI agents"
  homepage "https://github.com/iugu/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iugu"
  bash_completion "completions/iugu.bash"
  fish_completion "completions/iugu.fish"
  zsh_completion "completions/_iugu"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/iugu"], must_succeed: false
    end
  end

  # No zap stanza required
end
